# Basic workflow to get started with Github Actions
name: Simple Command Line Execution
#Controls when the workflow will run
on:
  push:
    branches: [main]
  workflow_dispatch:
# Workflows are made of 1 or Many Jobs
# They can also be in parallel
jobs:
  job1:
    name: Step 1
    runs-on: ubuntu-latest
    # The Sequence of steps
    steps:
    #Checks-out your repo under $GITHUB_WORKSPACE
    #this way, the job can access it
    - uses: actions/checkout@v2
    
    # Run a simple single command
    - name: Run a simple echo!
      run: echo Nebula, Pulsar, Quasar, Assemble!
  job2:
    name: Step 2
    runs-on: ubuntu-latest
    steps:
    - name: Run Hello
      run: echo Hello, Cosmos!
    - name: Sleepy time
      run: sleep 5


